# Generated by Django 6.0.6 on 2026-07-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_custom_user_updates_and_new_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_user_id_2a1528_idx',
            old_name='core_auditl_user_id_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action_f07419_idx',
            old_name='core_auditl_action_timestamp_idx',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx'),
        ),
    ]
