# Generated by Django 6.0.6 on 2026-07-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_core_auditl_user_id_timestamp_idx_core_auditl_user_id_2a1528_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
