# Generated by Django 6.0.6 on 2026-07-08 12:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recoverycode_securityquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
    ]
